name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)

pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/*

steps:

  - task: NuGetCommand@2
    displayName: Restore NuGet
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: Build Solution
    inputs:
      solution: '**\*.sln'
      configuration: 'release'

  - task: VSTest@2
    displayName: Execute Unit Tests
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\*.Tests.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      codeCoverageEnabled: true
      testRunTitle: '$(Build.BuildNumber)'
