namespace CloudAwesome.MarkdownMaker.Docusaurus;

/// <summary>
/// Model as defined here: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-front-matter
/// </summary>
public class MdDocuFrontMatterDocs: IFrontMatter
{
	/// <summary>
	/// A unique document ID.
	/// </summary>
	public string? id { get; set; }
	
	/// <summary>
	/// The text title of your document. Used for the page metadata and as a fallback value in multiple places (sidebar, next/previous buttons...). Automatically added at the top of your doc if it does not contain any Markdown title.
	/// </summary>
	public string? title { get; set; }
	
	/// <summary>
	/// The text used in the document next/previous buttons for this document.
	/// </summary>
	public string? pagination_label { get; set; }
	
	/// <summary>
	/// The text shown in the document sidebar for this document.
	/// </summary>
	public string? sidebar_label { get; set; }
	
	/// <summary>
	/// Controls the position of a doc inside the generated sidebar slice when using autogenerated sidebar items.
	/// </summary>
	public int? sidebar_position { get; set; }
	
	/// <summary>
	/// Gives the corresponding sidebar label a special class name when using autogenerated sidebars.
	/// </summary>
	public string? sidebar_class_name { get; set; }
	
	/// <summary>
	/// Gives the corresponding sidebar item a key to uniquely identify the sidebar item. This is mostly useful for i18n sites to generate unique translation keys for categories sharing the same labels. An error will tell you when this extra metadata is needed.
	/// </summary>
	public string? sidebar_key { get; set; }
	
	/// <summary>
	/// 	Assign custom props to the sidebar item referencing this doc
	/// </summary>
	public object? sidebar_custom_props { get; set; }
	
	/// <summary>
	/// Force the display of a given sidebar when browsing the current document. Read the multiple sidebars guide for details.
	/// </summary>
	public string? displayed_sidebar { get; set; }
	
	/// <summary>
	/// 	Whether to hide the title at the top of the doc. It only hides a title declared through the front matter, and have no effect on a Markdown title at the top of your document.
	/// </summary>
	public bool? hide_title { get; set; }
	
	/// <summary>
	/// Whether to hide the table of contents to the right.
	/// </summary>
	public bool? hide_table_of_contents { get; set; }
	
	/// <summary>
	/// The minimum heading level shown in the table of contents. Must be between 2 and 6 and lower or equal to the max value.
	/// </summary>
	public int? toc_min_heading_level { get; set; }
	
	/// <summary>
	/// The max heading level shown in the table of contents. Must be between 2 and 6.
	/// </summary>
	public int? toc_max_heading_level { get; set; }
	
	/// <summary>
	/// The ID of the documentation you want the "Next" pagination to link to. Use null to disable showing "Next" for this page.
	/// </summary>
	public string? pagination_next { get; set; }
	
	/// <summary>
	/// The ID of the documentation you want the "Previous" pagination to link to. Use null to disable showing "Previous" for this page.
	/// </summary>
	public string? pagination_prev { get; set; }
	
	/// <summary>
	/// Whether number prefix parsing is disabled on this doc.
	/// </summary>
	public bool? parse_number_prefixes { get; set; }
	
	/// <summary>
	/// The URL for editing this document. Use null to disable showing "Edit this page" for this page.
	/// </summary>
	public string? custom_edit_url { get; set; }
	
	/// <summary>
	/// Keywords meta tag for the document page, for search engines.
	/// </summary>
	public string[]? keywords { get; set; }
	
	/// <summary>
	/// The description of your document, which will become the <meta name="description" content="..."/> and <meta property="og:description" content="..."/> in <head>, used by search engines.
	/// </summary>
	public string? description { get; set; }
	
	/// <summary>
	/// Cover or thumbnail image that will be used as the <meta property="og:image" content="..."/> in the <head>, enhancing link previews on social media and messaging platforms.
	/// </summary>
	public string? image { get; set; }
	
	/// <summary>
	/// 	Allows to customize the document URL (/<routeBasePath>/<slug>). Support multiple patterns: slug: my-doc, slug: /my/path/myDoc, slug: /.
	/// </summary>
	public string? slug { get; set; }
	
	/// <summary>
	/// A list of strings.
	/// </summary>
	public string[]? tags { get; set; }
	
	/// <summary>
	/// Draft documents will only be available during development.
	/// </summary>
	public bool? draft { get; set; }
	
	/// <summary>
	/// Unlisted documents will be available in both development and production. They will be "hidden" in production, not indexed, excluded from sitemaps, and can only be accessed by users having a direct link.
	/// </summary>
	public bool? unlisted { get; set; }
	
	/// <summary>
	/// Allows overriding the last update author/date. Date can be any parsable date string.
	/// </summary>
	public FrontMatterLastUpdate? last_update { get; set; }
	
}

public class FrontMatterLastUpdate
{
	public string? date { get; set; }
	public string? author { get; set; }
}

